name: Android CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Install NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
          unzip android-ndk-r16b-linux-x86_64.zip
          mv android-ndk-r16b $HOME/android-ndk
          echo "ndk.dir=$HOME/android-ndk" >> $GITHUB_WORKSPACE/local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x Airplay_Main/gradlew
      - name: Build Apk
        run: cd Airplay_Main && ./gradlew assemble

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Add this step before using jq
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract APK file name
        id: extract_apk
        run: |
          APK_PATH=$(jq -r '.elements[0].outputFile' Airplay_Main/app/build/outputs/apk/release/output.json)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ env.APK_PATH }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APK_PATH }}
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive