name: Android CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # 只有在 tag push 的时候才会触发构建，构建后发布 普通提交不需要构建
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            .gradle/caches
            .gradle/wrapper

      - name: Install NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
          unzip android-ndk-r16b-linux-x86_64.zip
          mv android-ndk-r16b $HOME/android-ndk
          echo "ndk.dir=$HOME/android-ndk" >> $GITHUB_WORKSPACE/local.properties
      # Add this step before using jq
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Grant execute permission for gradlew
        run: chmod +x Airplay_Main/gradlew
      - name: Build Apk
        id: assemble_apk
        run: |
          cd Airplay_Main && ./gradlew assemble
          APK_PATH="$(pwd)/app/build/outputs/apk/release/$(jq -r '.[0].path' app/build/outputs/apk/release/output.json)"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
    outputs:
      apk_path: ${{ steps.assemble_apk.outputs.apk_path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          if-no-files-found: error
          path: ${{ needs.build.outputs.apk_path }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.build.outputs.apk_path }}
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive